name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: CapGuizera
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push das mudanças
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando a animação da cobrinha 🐍"
          add: "dist/github-contribution-grid-snake.svg"
